version: '3.6'


services:
  Boilerplate-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:Port1;http://+:Port0
      - ASPNETCORE_Kestrel__Certificates__Default__Password=yourpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DefaultConnection=Host=db-server;Port=5432;Database=HeroDb;Username=app_user;Password=myHardCoreDevDb123
    ports:
      - "Port1:Port1"
      - "Port0:Port0"
    volumes:
      - ./https:/https/:ro
    networks:
      - localdev